# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
os:
  - linux
julia:
  - release
  - 0.4.6
notifications:
  email: false
install:
  - sudo pip install awscli
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SimpleTasks"); Pkg.test("SimpleTasks"; coverage=true)'
